### ISSUE TITLE
Use feature gates to support older tibrv versions

### ISSUE THREAD

**Issue by bradfier** [bradfier/tibrv-rs#16]
Follow up from #15 

We need to pick a TIBCO release as our minimum supported version and gate features so we can build against anything after that.

> 
> So after looking at how `gtk-rs` does this, it doesn't [look quite such a pain](https://github.com/gtk-rs/gtk/blob/6fa2ec12239ab6f6abfc9a00193c25e14e526a86/Cargo.toml#L26-L41).
> Since you can define a feature flag as also enabling another we can chain them quite nicely.
> 
> In GTK they define a 'lowest common denominator' version of `3.4` and any newer version require you to opt in, so I'd like to follow that pattern here, that way it "just works" unless you explicitly need some of the new features in later versions.
> 
> So a question: what version do we pick as our base? I looked at [TIBCO's Documentation](http://supportinfo.tibco.com/docs/TIBCOEndofSupportInformation.pdf) to get an idea of what the oldest supported version is, but even `8.3` is considered EoL.
> 
> I currently build against `8.3.2` from August 2011, so if you're using `8.1.x` that must be from around 2008?
> 
> I can't find a set of release notes prior to 8.2, so I looked for the major changes from that version onward:
> ```
> 8.2.x: Vector Listeners (tibrvEvent_CreateVectorListener)
> 8.3.x: IPM Mode & POSIX Sockets
> ```
> `8.4.4`  deprecates support for PGM mode but other than that there aren't any major changes after `8.3` from our point of view.
> 
> Have you seen any other differences apart from the missing enum variants?

**Comment by bradfier** [comment]
@pfernie can you try building against your 8.1 lib with [feature-gate](https://github.com/bradfier/tibrv-rs/compare/master...feature-gate)?

**Comment by pfernie** [comment]
@bradfier: this works; I'm able to build without specifying any features, while `cargo build --features "tibrv_8_3"` produces errors as expected.

`8.1.x` is indeed 2008-vintage (hooray legacy systems), and 10 years seems reasonable for specifying a minimum version.

I reviewed the release notes I have which have details on `8.1` and `8.0`, but did not see any obvious items related to the C API. So we may be able to claim `8.0` as minimum version, and users that find different can always submit an issue/PR ;).

Also, note that some of the items I tagged as `tibrv_8_3` may actually be present in `8.2.x`, I just don't have that available to check.

**Comment by bradfier** [comment]
Do you think it's reasonable to declare support for something that we can't easily test? I don't have an archive lying around for anything earlier than 8.3.2

I'd like to get this finalised for a breaking `0.4.0` release, to include all your recent enhancements, with a view to implementing Request/Response INBOXs for `0.5.0`. After that, I'd like to think about what needs stabilized before declaring `1.0` and losing the ability to easily mess with the API.

**Comment by pfernie** [comment]
You're right, it would be best to advertise support only for what can be tested; my comment about `8.0` was only considering what might build. If other users with earlier versions make themselves available to troubleshoot and test, support could be added, I suppose. That may be tricky to do after the fact with the feature gating scheme, but given the age of `8.1` IMO it is probably not worth trying to pre-plan for such...

Although, it may be worthwhile to note that there is a "support gap" w.r.t. `8.2`...

**Comment by bradfier** [comment]
Given that `8.1` was released in 2008, I think I agree that 10 years is a sufficient backwards compatibility period.
I think we should just go with `8.1` as the minimum supported version, and include a note that `8.2` is untested due to unavailability of the components.

**Comment by pfernie** [comment]
:+1:

**Comment by bradfier** [comment]
Implemented in #17
