### ISSUE TITLE
`rustfmt` policy

### ISSUE THREAD

**Issue by pfernie** [bradfier/tibrv-rs#23]
[Rust 1.2.4](https://blog.rust-lang.org/2018/02/15/Rust-1.24.html) started shipping `rustfmt-preview` back in February, but it is still pre-`1.0`. I don't follow it closely, but my impression is a lot of the actual style [guidelines](https://github.com/rust-lang-nursery/fmt-rfcs/blob/master/guide/guide.md) are pretty much set now (100 character linewidth, for that particular religious war :wink:). But customizable via `rustfmt.toml` (`max_width=88`).

Currently, running both the `stable` and `nightly` versions seem to produce pretty modest diffs for `tibrv-rs` and `tibrv-sys-rs`, mainly re-arranging some longer argument lists to multiline.

**Comment by bradfier** [comment]
This is probably also worth a 'CONTRIBUTING.md', just in case there's ever a third user.

**Comment by bradfier** [comment]
I kinda dropped this on the floor a few weeks ago, sorry.

I did a once over with `cargo fmt` and fixed Travis properly, so any PRs should build properly now, I'll produce a CONTRIBUTING.md over the next few.

**Comment by bradfier** [comment]
I added [CONTRIBUTING.md](../CONTRIBUTING.md) and decided on using the defaults for `cargo fmt`...
