### ISSUE TITLE
function not loaded: clang_Type_getNumTemplateArguments

### ISSUE THREAD

**Issue by antback** [bradfier/tibrv-rs#27]
Hi,

Thanks a lot for sharing your work. I'm getting an error during build. Could you please share the versions of your environment? OS, Rust, etc. I think that this could be the cause.

I'm running:
- Red Hat Enterprise Linux Server release 7.7
- cargo 1.37.0
- tibrv8.4

You can get the full log here:

[cargo_error.txt](https://github.com/bradfier/tibrv-rs/files/4153932/cargo_error.txt)

**Comment by antback** [comment]
Fixed with more actual version of clang:

clang version 5.0.1 (tags/RELEASE_501/final)

**Comment by bradfier** [comment]
Thanks for your interest! I had to go down a bit of a rabbit hole to check this builds properly, [v0.6.0](https://github.com/bradfier/tibrv-rs/releases/tag/v0.6.0) which I just released is a result of this...

To answer your question, it (now) builds on my system with the following versions:

- Arch Linux
- rustc 1.41.0 (5e1a79984 2020-01-27)
- cargo 1.41.0 (626f0f40e 2019-12-03)
- clang version 9.0.1


What version do you see when you run `clang --version`? You need at least libclang 3.7 for bindgen to work properly, preferably >= 3.9.

See their requirements doc here: https://rust-lang.github.io/rust-bindgen/requirements.html

**Comment by bradfier** [comment]
Glad you were able to get it working!
